# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es
  contentDir: content/es
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
main:
  - name: Bio
    url: /
    weight: 10
  - name: Artículos
    url: /#papers
    weight: 11
  - name: Charlas
    url: /#talks
    weight: 12
  - name: Noticias
    url: /#news
    weight: 13
  - name: Experiencia
    url: experience/
    weight: 20
  - name: Proyectos
    url: projects/
    weight: 30
  - name: Enseñanza
    url: teaching/
    weight: 40
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
